syntax = "proto3";

package dealership.grpc;

option java_multiple_files = true;
option java_package = "dealership.common.grpc";
option java_outer_classname = "CarServiceProto";

service CarGrpcService {
  rpc GetAvailableCars (GetAvailableCarsRequest) returns (GetAvailableCarsResponse);
  rpc GetCarById (GetCarByIdRequest) returns (CarDto);
  rpc ReserveCar (ReserveCarRequest) returns (ReservationResponse);
  rpc ConfirmCar (ConfirmCarRequest) returns (ReservationResponse);
  rpc ReleaseCar (ReleaseCarRequest) returns (ReservationResponse);
  rpc QuoteConfiguration (QuoteConfigurationRequest) returns (QuoteConfigurationResponse);
}

message GetAvailableCarsRequest {
}

message GetAvailableCarsResponse {
  repeated CarDto cars = 1;
}

message GetCarByIdRequest {
  string id = 1;
}

message ReserveCarRequest {
  string car_id = 1;
  string order_id = 2;
}

message ReleaseCarRequest {
  string car_id = 1;
  string order_id = 2;
}

message ConfirmCarRequest {
  string car_id = 1;
  string order_id = 2;
}

message ReservationResponse {
  bool successful = 1;
  int64 expires_at_epoch_millis = 2;
}

message QuoteConfigurationRequest {
  string car_model_id = 1;
  map<string, string> selected_variants = 2;
}

message QuoteConfigurationResponse {
  string car_model_id = 1;
  map<string, string> selected_variants = 2;
  string total_price = 3;
}

message CarDto {
  string id = 1;
  string brand = 2;
  string model_name = 3;
  string body_type = 4;
  string fuel_type = 5;
  int32 engine_power_hp = 6;
  double engine_volume_liters = 7;
  string transmission_type = 8;
  string drive_type = 9;
  string color = 10;
  string price = 11;
  bool available = 12;
  bool available_for_test_drive = 13;
}
